version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/project/
hooks:
  AfterInstall:
    - location: /afterInstall.sh
      timeout: 3000
      runas: ec2-user
  ApplicationStart:
    - location: /applicationStart.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: /applicationStop.sh
      timeout: 300
      runas: ec2-user
