version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo installing node dependencies
      - npm install
      - npm run installClient
  build:
    commands:
      - echo building the file
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-path: no
